// Generated by gencpp from file messages_pkg/Motor_settings.msg
// DO NOT EDIT!


#ifndef MESSAGES_PKG_MESSAGE_MOTOR_SETTINGS_H
#define MESSAGES_PKG_MESSAGE_MOTOR_SETTINGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages_pkg
{
template <class ContainerAllocator>
struct Motor_settings_
{
  typedef Motor_settings_<ContainerAllocator> Type;

  Motor_settings_()
    : KP(0.0)
    , KI(0.0)
    , KD(0.0)  {
    }
  Motor_settings_(const ContainerAllocator& _alloc)
    : KP(0.0)
    , KI(0.0)
    , KD(0.0)  {
  (void)_alloc;
    }



   typedef double _KP_type;
  _KP_type KP;

   typedef double _KI_type;
  _KI_type KI;

   typedef double _KD_type;
  _KD_type KD;





  typedef boost::shared_ptr< ::messages_pkg::Motor_settings_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages_pkg::Motor_settings_<ContainerAllocator> const> ConstPtr;

}; // struct Motor_settings_

typedef ::messages_pkg::Motor_settings_<std::allocator<void> > Motor_settings;

typedef boost::shared_ptr< ::messages_pkg::Motor_settings > Motor_settingsPtr;
typedef boost::shared_ptr< ::messages_pkg::Motor_settings const> Motor_settingsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages_pkg::Motor_settings_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages_pkg::Motor_settings_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messages_pkg::Motor_settings_<ContainerAllocator1> & lhs, const ::messages_pkg::Motor_settings_<ContainerAllocator2> & rhs)
{
  return lhs.KP == rhs.KP &&
    lhs.KI == rhs.KI &&
    lhs.KD == rhs.KD;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messages_pkg::Motor_settings_<ContainerAllocator1> & lhs, const ::messages_pkg::Motor_settings_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messages_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::messages_pkg::Motor_settings_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages_pkg::Motor_settings_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages_pkg::Motor_settings_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages_pkg::Motor_settings_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages_pkg::Motor_settings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages_pkg::Motor_settings_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages_pkg::Motor_settings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "136a480595a5448a1d1b3eef5d307252";
  }

  static const char* value(const ::messages_pkg::Motor_settings_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x136a480595a5448aULL;
  static const uint64_t static_value2 = 0x1d1b3eef5d307252ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages_pkg::Motor_settings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages_pkg/Motor_settings";
  }

  static const char* value(const ::messages_pkg::Motor_settings_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages_pkg::Motor_settings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 KP\n"
"float64 KI\n"
"float64 KD\n"
;
  }

  static const char* value(const ::messages_pkg::Motor_settings_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages_pkg::Motor_settings_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.KP);
      stream.next(m.KI);
      stream.next(m.KD);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Motor_settings_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages_pkg::Motor_settings_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages_pkg::Motor_settings_<ContainerAllocator>& v)
  {
    s << indent << "KP: ";
    Printer<double>::stream(s, indent + "  ", v.KP);
    s << indent << "KI: ";
    Printer<double>::stream(s, indent + "  ", v.KI);
    s << indent << "KD: ";
    Printer<double>::stream(s, indent + "  ", v.KD);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_PKG_MESSAGE_MOTOR_SETTINGS_H
