// Generated by gencpp from file messages_pkg/Motor_values.msg
// DO NOT EDIT!


#ifndef MESSAGES_PKG_MESSAGE_MOTOR_VALUES_H
#define MESSAGES_PKG_MESSAGE_MOTOR_VALUES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages_pkg
{
template <class ContainerAllocator>
struct Motor_values_
{
  typedef Motor_values_<ContainerAllocator> Type;

  Motor_values_()
    : motor1_value(0.0)
    , motor2_value(0.0)
    , OnOff(0)  {
    }
  Motor_values_(const ContainerAllocator& _alloc)
    : motor1_value(0.0)
    , motor2_value(0.0)
    , OnOff(0)  {
  (void)_alloc;
    }



   typedef float _motor1_value_type;
  _motor1_value_type motor1_value;

   typedef float _motor2_value_type;
  _motor2_value_type motor2_value;

   typedef int16_t _OnOff_type;
  _OnOff_type OnOff;





  typedef boost::shared_ptr< ::messages_pkg::Motor_values_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages_pkg::Motor_values_<ContainerAllocator> const> ConstPtr;

}; // struct Motor_values_

typedef ::messages_pkg::Motor_values_<std::allocator<void> > Motor_values;

typedef boost::shared_ptr< ::messages_pkg::Motor_values > Motor_valuesPtr;
typedef boost::shared_ptr< ::messages_pkg::Motor_values const> Motor_valuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages_pkg::Motor_values_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages_pkg::Motor_values_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messages_pkg::Motor_values_<ContainerAllocator1> & lhs, const ::messages_pkg::Motor_values_<ContainerAllocator2> & rhs)
{
  return lhs.motor1_value == rhs.motor1_value &&
    lhs.motor2_value == rhs.motor2_value &&
    lhs.OnOff == rhs.OnOff;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messages_pkg::Motor_values_<ContainerAllocator1> & lhs, const ::messages_pkg::Motor_values_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messages_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::messages_pkg::Motor_values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages_pkg::Motor_values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages_pkg::Motor_values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages_pkg::Motor_values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages_pkg::Motor_values_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages_pkg::Motor_values_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages_pkg::Motor_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12eba4c10619ee8f4c0326813788bdcb";
  }

  static const char* value(const ::messages_pkg::Motor_values_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12eba4c10619ee8fULL;
  static const uint64_t static_value2 = 0x4c0326813788bdcbULL;
};

template<class ContainerAllocator>
struct DataType< ::messages_pkg::Motor_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages_pkg/Motor_values";
  }

  static const char* value(const ::messages_pkg::Motor_values_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages_pkg::Motor_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 motor1_value\n"
"float32 motor2_value\n"
"int16 OnOff\n"
;
  }

  static const char* value(const ::messages_pkg::Motor_values_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages_pkg::Motor_values_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor1_value);
      stream.next(m.motor2_value);
      stream.next(m.OnOff);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Motor_values_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages_pkg::Motor_values_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages_pkg::Motor_values_<ContainerAllocator>& v)
  {
    s << indent << "motor1_value: ";
    Printer<float>::stream(s, indent + "  ", v.motor1_value);
    s << indent << "motor2_value: ";
    Printer<float>::stream(s, indent + "  ", v.motor2_value);
    s << indent << "OnOff: ";
    Printer<int16_t>::stream(s, indent + "  ", v.OnOff);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_PKG_MESSAGE_MOTOR_VALUES_H
