// Generated by gencpp from file rqt_mypkg/Angles.msg
// DO NOT EDIT!


#ifndef RQT_MYPKG_MESSAGE_ANGLES_H
#define RQT_MYPKG_MESSAGE_ANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rqt_mypkg
{
template <class ContainerAllocator>
struct Angles_
{
  typedef Angles_<ContainerAllocator> Type;

  Angles_()
    : leg1_angle(0.0)
    , leg2_angle(0.0)  {
    }
  Angles_(const ContainerAllocator& _alloc)
    : leg1_angle(0.0)
    , leg2_angle(0.0)  {
  (void)_alloc;
    }



   typedef double _leg1_angle_type;
  _leg1_angle_type leg1_angle;

   typedef double _leg2_angle_type;
  _leg2_angle_type leg2_angle;





  typedef boost::shared_ptr< ::rqt_mypkg::Angles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rqt_mypkg::Angles_<ContainerAllocator> const> ConstPtr;

}; // struct Angles_

typedef ::rqt_mypkg::Angles_<std::allocator<void> > Angles;

typedef boost::shared_ptr< ::rqt_mypkg::Angles > AnglesPtr;
typedef boost::shared_ptr< ::rqt_mypkg::Angles const> AnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rqt_mypkg::Angles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rqt_mypkg::Angles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rqt_mypkg::Angles_<ContainerAllocator1> & lhs, const ::rqt_mypkg::Angles_<ContainerAllocator2> & rhs)
{
  return lhs.leg1_angle == rhs.leg1_angle &&
    lhs.leg2_angle == rhs.leg2_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rqt_mypkg::Angles_<ContainerAllocator1> & lhs, const ::rqt_mypkg::Angles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rqt_mypkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rqt_mypkg::Angles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rqt_mypkg::Angles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rqt_mypkg::Angles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rqt_mypkg::Angles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rqt_mypkg::Angles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rqt_mypkg::Angles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rqt_mypkg::Angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "985254c41e9ddd9bde0a2cf0dd651229";
  }

  static const char* value(const ::rqt_mypkg::Angles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x985254c41e9ddd9bULL;
  static const uint64_t static_value2 = 0xde0a2cf0dd651229ULL;
};

template<class ContainerAllocator>
struct DataType< ::rqt_mypkg::Angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rqt_mypkg/Angles";
  }

  static const char* value(const ::rqt_mypkg::Angles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rqt_mypkg::Angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 leg1_angle\n"
"float64 leg2_angle\n"
;
  }

  static const char* value(const ::rqt_mypkg::Angles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rqt_mypkg::Angles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leg1_angle);
      stream.next(m.leg2_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Angles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rqt_mypkg::Angles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rqt_mypkg::Angles_<ContainerAllocator>& v)
  {
    s << indent << "leg1_angle: ";
    Printer<double>::stream(s, indent + "  ", v.leg1_angle);
    s << indent << "leg2_angle: ";
    Printer<double>::stream(s, indent + "  ", v.leg2_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RQT_MYPKG_MESSAGE_ANGLES_H
