// Generated by gencpp from file rqt_mypkg/motor_values.msg
// DO NOT EDIT!


#ifndef RQT_MYPKG_MESSAGE_MOTOR_VALUES_H
#define RQT_MYPKG_MESSAGE_MOTOR_VALUES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rqt_mypkg
{
template <class ContainerAllocator>
struct motor_values_
{
  typedef motor_values_<ContainerAllocator> Type;

  motor_values_()
    : motor1_value(0.0)
    , motor2_value(0.0)  {
    }
  motor_values_(const ContainerAllocator& _alloc)
    : motor1_value(0.0)
    , motor2_value(0.0)  {
  (void)_alloc;
    }



   typedef float _motor1_value_type;
  _motor1_value_type motor1_value;

   typedef float _motor2_value_type;
  _motor2_value_type motor2_value;





  typedef boost::shared_ptr< ::rqt_mypkg::motor_values_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rqt_mypkg::motor_values_<ContainerAllocator> const> ConstPtr;

}; // struct motor_values_

typedef ::rqt_mypkg::motor_values_<std::allocator<void> > motor_values;

typedef boost::shared_ptr< ::rqt_mypkg::motor_values > motor_valuesPtr;
typedef boost::shared_ptr< ::rqt_mypkg::motor_values const> motor_valuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rqt_mypkg::motor_values_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rqt_mypkg::motor_values_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rqt_mypkg::motor_values_<ContainerAllocator1> & lhs, const ::rqt_mypkg::motor_values_<ContainerAllocator2> & rhs)
{
  return lhs.motor1_value == rhs.motor1_value &&
    lhs.motor2_value == rhs.motor2_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rqt_mypkg::motor_values_<ContainerAllocator1> & lhs, const ::rqt_mypkg::motor_values_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rqt_mypkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rqt_mypkg::motor_values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rqt_mypkg::motor_values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rqt_mypkg::motor_values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rqt_mypkg::motor_values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rqt_mypkg::motor_values_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rqt_mypkg::motor_values_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rqt_mypkg::motor_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0030d48ec79b36863e9007b5cb915eb";
  }

  static const char* value(const ::rqt_mypkg::motor_values_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0030d48ec79b368ULL;
  static const uint64_t static_value2 = 0x63e9007b5cb915ebULL;
};

template<class ContainerAllocator>
struct DataType< ::rqt_mypkg::motor_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rqt_mypkg/motor_values";
  }

  static const char* value(const ::rqt_mypkg::motor_values_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rqt_mypkg::motor_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 motor1_value\n"
"float32 motor2_value\n"
;
  }

  static const char* value(const ::rqt_mypkg::motor_values_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rqt_mypkg::motor_values_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor1_value);
      stream.next(m.motor2_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_values_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rqt_mypkg::motor_values_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rqt_mypkg::motor_values_<ContainerAllocator>& v)
  {
    s << indent << "motor1_value: ";
    Printer<float>::stream(s, indent + "  ", v.motor1_value);
    s << indent << "motor2_value: ";
    Printer<float>::stream(s, indent + "  ", v.motor2_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RQT_MYPKG_MESSAGE_MOTOR_VALUES_H
